/*
 * Copyright (c), Recep Aslantas.
 *
 * MIT License (MIT), http://opensource.org/licenses/MIT
 * Full license can be found in the LICENSE file
 */

#ifndef gltf_strpool_h
#  define gltf_strpool_h

#ifndef _AK_GLTF_STRPOOL_
#  define _AK_EXTERN extern
#else
#  define _AK_EXTERN
#endif

_AK_EXTERN const char _s_gltf_pool_0[];

#define _s_gltf_0(x) (_s_gltf_pool_0 + x)

/* _s_gltf_pool_0 */
#define _s_gltf_space _s_gltf_0(0)
#define _s_gltf_gltf _s_gltf_0(2)
#define _s_gltf_asset _s_gltf_0(7)
#define _s_gltf_version _s_gltf_0(13)
#define _s_gltf_generator _s_gltf_0(21)
#define _s_gltf_copyright _s_gltf_0(31)
#define _s_gltf_meter _s_gltf_0(41)
#define _s_gltf_buffers _s_gltf_0(47)
#define _s_gltf_uri _s_gltf_0(55)
#define _s_gltf_byteLength _s_gltf_0(59)
#define _s_gltf_bufferViews _s_gltf_0(70)
#define _s_gltf_buffer _s_gltf_0(82)
#define _s_gltf_byteOffset _s_gltf_0(89)
#define _s_gltf_byteStride _s_gltf_0(100)
#define _s_gltf_bufferView _s_gltf_0(111)
#define _s_gltf_componentType _s_gltf_0(122)
#define _s_gltf_normalized _s_gltf_0(136)
#define _s_gltf_count _s_gltf_0(147)
#define _s_gltf_type _s_gltf_0(153)
#define _s_gltf_max _s_gltf_0(158)
#define _s_gltf_min _s_gltf_0(162)
#define _s_gltf_meshes _s_gltf_0(166)
#define _s_gltf_primitives _s_gltf_0(173)
#define _s_gltf_attributes _s_gltf_0(184)
#define _s_gltf_indices _s_gltf_0(195)
#define _s_gltf_mode _s_gltf_0(203)
#define _s_gltf_nodes _s_gltf_0(208)
#define _s_gltf_node _s_gltf_0(214)
#define _s_gltf_mesh _s_gltf_0(219)
#define _s_gltf_scene _s_gltf_0(224)
#define _s_gltf_scenes _s_gltf_0(230)
#define _s_gltf_name _s_gltf_0(237)
#define _s_gltf_accessors _s_gltf_0(242)
#define _s_gltf_POSITION _s_gltf_0(252)
#define _s_gltf_NORMAL _s_gltf_0(261)
#define _s_gltf_TANGENT _s_gltf_0(268)
#define _s_gltf_TEXCOORD _s_gltf_0(276)
#define _s_gltf_COLOR _s_gltf_0(285)
#define _s_gltf_JOINTS _s_gltf_0(291)
#define _s_gltf_WEIGHTS _s_gltf_0(298)
#define _s_gltf_SCALAR _s_gltf_0(306)
#define _s_gltf_VEC2 _s_gltf_0(313)
#define _s_gltf_VEC3 _s_gltf_0(318)
#define _s_gltf_VEC4 _s_gltf_0(323)
#define _s_gltf_MAT2 _s_gltf_0(328)
#define _s_gltf_MAT3 _s_gltf_0(333)
#define _s_gltf_MAT4 _s_gltf_0(338)
#define _s_gltf_children _s_gltf_0(343)
#define _s_gltf_matrix _s_gltf_0(352)
#define _s_gltf_rotation _s_gltf_0(359)
#define _s_gltf_scale _s_gltf_0(368)
#define _s_gltf_translation _s_gltf_0(374)
#define _s_gltf_weights _s_gltf_0(386)
#define _s_gltf_extensions _s_gltf_0(394)
#define _s_gltf_extras _s_gltf_0(405)
#define _s_gltf_skin _s_gltf_0(412)
#define _s_gltf_camera _s_gltf_0(417)
#define _s_gltf_cameras _s_gltf_0(424)
#define _s_gltf_perspective _s_gltf_0(432)
#define _s_gltf_orthographic _s_gltf_0(444)
#define _s_gltf_aspectRatio _s_gltf_0(457)
#define _s_gltf_xfov _s_gltf_0(469)
#define _s_gltf_yfov _s_gltf_0(474)
#define _s_gltf_zfar _s_gltf_0(479)
#define _s_gltf_znear _s_gltf_0(484)
#define _s_gltf_xmag _s_gltf_0(490)
#define _s_gltf_ymag _s_gltf_0(495)
#define _s_gltf_ak_flg _s_gltf_0(500)
#define _s_gltf_VERTEX _s_gltf_0(507)
#define _s_gltf_images _s_gltf_0(514)
#define _s_gltf_image _s_gltf_0(521)
#define _s_gltf_sampler _s_gltf_0(527)
#define _s_gltf_samplers _s_gltf_0(535)
#define _s_gltf_wrapS _s_gltf_0(544)
#define _s_gltf_wrapT _s_gltf_0(550)
#define _s_gltf_magFilter _s_gltf_0(556)
#define _s_gltf_minFilter _s_gltf_0(566)
#define _s_gltf_textures _s_gltf_0(576)
#define _s_gltf_source _s_gltf_0(585)
#define _s_gltf_material _s_gltf_0(592)
#define _s_gltf_materials _s_gltf_0(601)
#define _s_gltf_pbrMetalRough _s_gltf_0(611)
#define _s_gltf_normalTex _s_gltf_0(632)
#define _s_gltf_occlusionTex _s_gltf_0(646)
#define _s_gltf_emissiveTex _s_gltf_0(663)
#define _s_gltf_emissiveFac _s_gltf_0(679)
#define _s_gltf_alphaMode _s_gltf_0(694)
#define _s_gltf_alphaCutoff _s_gltf_0(704)
#define _s_gltf_doubleSided _s_gltf_0(716)
#define _s_gltf_baseColor _s_gltf_0(728)
#define _s_gltf_baseColorTex _s_gltf_0(744)
#define _s_gltf_metalFac _s_gltf_0(761)
#define _s_gltf_roughFac _s_gltf_0(776)
#define _s_gltf_metalRoughTex _s_gltf_0(792)
#define _s_gltf_index _s_gltf_0(817)
#define _s_gltf_texCoord _s_gltf_0(823)
#define _s_gltf_sid_texcoord _s_gltf_0(832)
#define _s_gltf_sid_sampler _s_gltf_0(836)
#define _s_gltf_id_metalrough _s_gltf_0(841)

#endif /* ak_gltf_strpool_h */
