/*
 * Copyright (C) 2020 Recep Aslantas
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef _AK_STRPOOL_
#  define _AK_STRPOOL_
#endif

#include "strpool.h"
#include <string.h>

const char _s_ak_pool_0[] =
"POSITION\0"
"NORMAL\0"
"TEXCOORD\0"
"COLOR\0"
"baseColor\0"
"opacity\0"
"metallic\0"
"roughness\0"
"normal\0"
"occlusion\0"
"emissive\0"
"alpha\0"
"albedo\0"
"diffuse\0"
"emission\0"
"metalness\0"
"ambient\0"
"specular\0"
"reflective\0"
"transparency\0"
"glossiness\0"
"specularFactor\0"
"specularColor\0"
"clearcoat\0"
"clearcoatRoughness\0"
"clearcoatNormal\0"
"transmission\0"
"sheenColor\0"
"sheenRoughness\0"
"iridescence\0"
"iridescenceThickness\0"
"thickness\0"
"multiscatterColor\0"
"anisotropyStrength\0"
"anisotropyRotation\0"
"diffuseTransmission\0"
"diffuseTransmissionColor\0"
"Id\0"
"Type\0"
"Target\0"
"TargetMode\0"
"color\0"
"displaycolor\0"
"displayname\0"
"ContentType\0"
"Extension\0"
"PartName\0"
"UUID\0"
"id\0"
"name\0"
"objectid\0"
"path\0"
"partnumber\0"
"modelresolution\0"
"requiredextensions\0"
"config\0"
"metadata\0"
"resources\0"
"build\0"
"object\0"
"mesh\0"
"vertices\0"
"vertex\0"
"triangles\0"
"triangle\0"
"part\0"
"key\0"
"value\0"
"extruder\0"
"filament_colour\0"
"paint_color\0"
"mmu_segmentation\0"
"p1\0"
"p2\0"
"p3\0"
"pid\0"
"pindex\0"
"transform\0"
"unit\0"
"v1\0"
"v2\0"
"v3\0"
"x\0"
"y\0"
"z\0"
"u\0"
"v\0"
"Vertex Color\0"
"Vertex Color Alpha\0"
"Relationship\0"
"Override\0"
"Default\0"
"model\0"
"base\0"
"basematerials\0"
"colorgroup\0"
"texture2d\0"
"texture2dgroup\0"
"tex2coord\0"
"compositematerials\0"
"multiproperties\0"
"multi\0"
"matid\0"
"matindices\0"
"values\0"
"pids\0"
"pindices\0"
"blendmethods\0"
"displaypropertiesid\0"
"texid\0"
"contenttype\0"
"imagestack\0"
"imagesheet\0"
"composite\0"
"materialmapping\0"
"property\0"
"image3d\0"
"functionfromimage3d\0"
"implicitfunction\0"
"volumedata\0"
"beam\0"
"ball\0"
"beamset\0"
"ref\0"
"ballref\0"
"beamlattice\0"
"beams\0"
"balls\0"
"beamsets\0"
"components\0"
"component\0"
"displacementmesh\0"
"booleanshape\0"
"levelset\0"
"boolean\0"
"normvector\0"
"disp2dcoord\0"
"displacement2d\0"
"normvectorgroup\0"
"disp2dgroup\0"
"polygon\0"
"segment\0"
"slicestack\0"
"sliceref\0"
"slice\0"
"alternatives\0"
"alternative\0"
"item\0"
;

#undef _AK_STRPOOL_
