/*
 * Copyright (C) 2020 Recep Aslantas
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef _GLTF_STRPOOL_
#  define _GLTF_STRPOOL_
#endif

#include "strpool.h"
#include <string.h>

const char _s_gltf_pool_0[] =
" \0"
"gltf\0"
"asset\0"
"version\0"
"generator\0"
"copyright\0"
"meter\0"
"buffers\0"
"uri\0"
"byteLength\0"
"bufferViews\0"
"buffer\0"
"byteOffset\0"
"byteStride\0"
"bufferView\0"
"componentType\0"
"normalized\0"
"count\0"
"type\0"
"max\0"
"min\0"
"meshes\0"
"primitives\0"
"attributes\0"
"indices\0"
"mode\0"
"nodes\0"
"node\0"
"mesh\0"
"scene\0"
"scenes\0"
"name\0"
"accessors\0"
"POSITION\0"
"NORMAL\0"
"TANGENT\0"
"TEXCOORD\0"
"COLOR\0"
"JOINTS\0"
"WEIGHTS\0"
"SCALAR\0"
"VEC2\0"
"VEC3\0"
"VEC4\0"
"MAT2\0"
"MAT3\0"
"MAT4\0"
"children\0"
"matrix\0"
"rotation\0"
"scale\0"
"translation\0"
"weights\0"
"extensions\0"
"extras\0"
"skin\0"
"morph\0"
"skins\0"
"camera\0"
"cameras\0"
"perspective\0"
"orthographic\0"
"aspectRatio\0"
"xfov\0"
"yfov\0"
"zfar\0"
"znear\0"
"xmag\0"
"ymag\0"
"ak_flg\0"
"VERTEX\0"
"images\0"
"image\0"
"sampler\0"
"samplers\0"
"wrapS\0"
"wrapT\0"
"magFilter\0"
"minFilter\0"
"textures\0"
"source\0"
"material\0"
"materials\0"
"pbrMetallicRoughness\0"
"normalTexture\0"
"occlusionTexture\0"
"strength\0"
"emissiveTexture\0"
"emissiveFactor\0"
"alphaMode\0"
"alphaCutoff\0"
"doubleSided\0"
"baseColorFactor\0"
"baseColorTexture\0"
"metallicFactor\0"
"roughnessFactor\0"
"metallicRoughnessTexture\0"
"index\0"
"texCoord\0"
"TEXCOORD\0"
"smp\0"
"specgloss\0"
"KHR_materials_pbrSpecularGlossiness\0"
"KHR_materials_specular\0"
"KHR_materials_ior\0"
"specularFactor\0"
"specularTexture\0"
"specularColorFactor\0"
"specularColorTexture\0"
"diffuseFactor\0"
"specularFactor\0"
"diffuseTexture\0"
"glossinessFactor\0"
"specularGlossinessTexture\0"
"BLEND\0"
"MASK\0"
"OPAQUE\0"
"animations\0"
"channels\0"
"target\0"
"targets\0"
"path\0"
"interpolation\0"
"input\0"
"output\0"
"anim\0"
"LINEAR\0"
"STEP\0"
"CUBICSPLINE\0"
"inverseBindMatrices\0"
"joints\0"
"sparse\0"
"data:\0"
;

#undef _GLTF_STRPOOL_
