/*
 * Copyright (C) 2020 Recep Aslantas
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef gltf_strpool_h
#  define gltf_strpool_h

#ifndef _GLTF_STRPOOL_
#  define _AK_EXTERN extern
#else
#  define _AK_EXTERN
#endif

_AK_EXTERN const char _s_gltf_pool_0[];
_AK_EXTERN const char _s_gltf_pool_1[];

#define _s_gltf_0(x) (_s_gltf_pool_0 + x)
#define _s_gltf_1(x) (_s_gltf_pool_1 + x)

/* _s_gltf_pool_0 */
#define _s_gltf_space _s_gltf_0(0)
#define _s_gltf_gltf _s_gltf_0(2)
#define _s_gltf_asset _s_gltf_0(7)
#define _s_gltf_version _s_gltf_0(13)
#define _s_gltf_generator _s_gltf_0(21)
#define _s_gltf_copyright _s_gltf_0(31)
#define _s_gltf_meter _s_gltf_0(41)
#define _s_gltf_buffers _s_gltf_0(47)
#define _s_gltf_uri _s_gltf_0(55)
#define _s_gltf_byteLength _s_gltf_0(59)
#define _s_gltf_bufferViews _s_gltf_0(70)
#define _s_gltf_buffer _s_gltf_0(82)
#define _s_gltf_byteOffset _s_gltf_0(89)
#define _s_gltf_byteStride _s_gltf_0(100)
#define _s_gltf_bufferView _s_gltf_0(111)
#define _s_gltf_componentType _s_gltf_0(122)
#define _s_gltf_normalized _s_gltf_0(136)
#define _s_gltf_count _s_gltf_0(147)
#define _s_gltf_type _s_gltf_0(153)
#define _s_gltf_max _s_gltf_0(158)
#define _s_gltf_min _s_gltf_0(162)
#define _s_gltf_values _s_gltf_0(166)
#define _s_gltf_meshes _s_gltf_0(173)
#define _s_gltf_primitives _s_gltf_0(180)
#define _s_gltf_attributes _s_gltf_0(191)
#define _s_gltf_indices _s_gltf_0(202)
#define _s_gltf_mode _s_gltf_0(210)
#define _s_gltf_nodes _s_gltf_0(215)
#define _s_gltf_node _s_gltf_0(221)
#define _s_gltf_mesh _s_gltf_0(226)
#define _s_gltf_scene _s_gltf_0(231)
#define _s_gltf_scenes _s_gltf_0(237)
#define _s_gltf_name _s_gltf_0(244)
#define _s_gltf_accessors _s_gltf_0(249)
#define _s_gltf_POSITION _s_gltf_0(259)
#define _s_gltf_NORMAL _s_gltf_0(268)
#define _s_gltf_TANGENT _s_gltf_0(275)
#define _s_gltf_TEXCOORD _s_gltf_0(283)
#define _s_gltf_COLOR _s_gltf_0(292)
#define _s_gltf_JOINTS _s_gltf_0(298)
#define _s_gltf_WEIGHTS _s_gltf_0(305)
#define _s_gltf_SCALAR _s_gltf_0(313)
#define _s_gltf_VEC2 _s_gltf_0(320)
#define _s_gltf_VEC3 _s_gltf_0(325)
#define _s_gltf_VEC4 _s_gltf_0(330)
#define _s_gltf_MAT2 _s_gltf_0(335)
#define _s_gltf_MAT3 _s_gltf_0(340)
#define _s_gltf_MAT4 _s_gltf_0(345)
#define _s_gltf_children _s_gltf_0(350)
#define _s_gltf_matrix _s_gltf_0(359)
#define _s_gltf_rotation _s_gltf_0(366)
#define _s_gltf_scale _s_gltf_0(375)
#define _s_gltf_translation _s_gltf_0(381)
#define _s_gltf_weights _s_gltf_0(393)
#define _s_gltf_extensions _s_gltf_0(401)
#define _s_gltf_extensionsUsed _s_gltf_0(412)
#define _s_gltf_extensionsRequired _s_gltf_0(427)
#define _s_gltf_extras _s_gltf_0(446)
#define _s_gltf_skin _s_gltf_0(453)
#define _s_gltf_morph _s_gltf_0(458)
#define _s_gltf_skins _s_gltf_0(464)
#define _s_gltf_camera _s_gltf_0(470)
#define _s_gltf_cameras _s_gltf_0(477)
#define _s_gltf_light _s_gltf_0(485)
#define _s_gltf_lights _s_gltf_0(491)
#define _s_gltf_visible _s_gltf_0(498)
#define _s_gltf_color _s_gltf_0(506)
#define _s_gltf_intensity _s_gltf_0(512)
#define _s_gltf_range _s_gltf_0(522)
#define _s_gltf_spot _s_gltf_0(528)
#define _s_gltf_innerConeAngle _s_gltf_0(533)
#define _s_gltf_outerConeAngle _s_gltf_0(548)
#define _s_gltf_directional _s_gltf_0(563)
#define _s_gltf_point _s_gltf_0(575)
#define _s_gltf_perspective _s_gltf_0(581)
#define _s_gltf_orthographic _s_gltf_0(593)
#define _s_gltf_aspectRatio _s_gltf_0(606)
#define _s_gltf_xfov _s_gltf_0(618)
#define _s_gltf_yfov _s_gltf_0(623)
#define _s_gltf_zfar _s_gltf_0(628)
#define _s_gltf_znear _s_gltf_0(633)
#define _s_gltf_xmag _s_gltf_0(639)
#define _s_gltf_ymag _s_gltf_0(644)
#define _s_gltf_ak_flg _s_gltf_0(649)
#define _s_gltf_VERTEX _s_gltf_0(656)
#define _s_gltf_images _s_gltf_0(663)
#define _s_gltf_image _s_gltf_0(670)
#define _s_gltf_sampler _s_gltf_0(676)
#define _s_gltf_samplers _s_gltf_0(684)
#define _s_gltf_wrapS _s_gltf_0(693)
#define _s_gltf_wrapT _s_gltf_0(699)
#define _s_gltf_magFilter _s_gltf_0(705)
#define _s_gltf_minFilter _s_gltf_0(715)
#define _s_gltf_textures _s_gltf_0(725)
#define _s_gltf_source _s_gltf_0(734)
#define _s_gltf_material _s_gltf_0(741)
#define _s_gltf_materials _s_gltf_0(750)
#define _s_gltf_pbrMetalRough _s_gltf_0(760)
#define _s_gltf_normalTex _s_gltf_0(781)
#define _s_gltf_occlusionTex _s_gltf_0(795)
#define _s_gltf_strength _s_gltf_0(812)
#define _s_gltf_emissiveTex _s_gltf_0(821)
#define _s_gltf_emissiveFac _s_gltf_0(837)
#define _s_gltf_alphaMode _s_gltf_0(852)
#define _s_gltf_alphaCutoff _s_gltf_0(862)
#define _s_gltf_doubleSided _s_gltf_0(874)
#define _s_gltf_baseColor _s_gltf_0(886)
#define _s_gltf_baseColorTex _s_gltf_0(902)
#define _s_gltf_metalFac _s_gltf_0(919)
#define _s_gltf_roughFac _s_gltf_0(934)
#define _s_gltf_metalRoughTex _s_gltf_0(950)
#define _s_gltf_index _s_gltf_0(975)
#define _s_gltf_texCoord _s_gltf_0(981)
#define _s_gltf_texcoordPrefix _s_gltf_0(990)
#define _s_gltf_sid_sampler _s_gltf_0(999)
#define _s_gltf_id_specgloss _s_gltf_0(1003)
#define _s_gltf_KHR_materials_pbrSpecularGlossiness _s_gltf_0(1013)
#define _s_gltf_KHR_materials_specular _s_gltf_0(1049)
#define _s_gltf_ext_KHR_materials_ior _s_gltf_0(1072)
#define _s_gltf_specularFactor _s_gltf_0(1090)
#define _s_gltf_specularTexture _s_gltf_0(1105)
#define _s_gltf_specularColorFactor _s_gltf_0(1121)
#define _s_gltf_specularColorTexture _s_gltf_0(1141)
#define _s_gltf_diffuseFactor _s_gltf_0(1162)
#define _s_gltf_specFactor _s_gltf_0(1176)
#define _s_gltf_diffuseTexture _s_gltf_0(1191)
#define _s_gltf_glossFactor _s_gltf_0(1206)
#define _s_gltf_specGlossTex _s_gltf_0(1223)
#define _s_gltf_BLEND _s_gltf_0(1249)
#define _s_gltf_MASK _s_gltf_0(1255)
#define _s_gltf_OPAQUE _s_gltf_0(1260)
#define _s_gltf_animations _s_gltf_0(1267)
#define _s_gltf_channels _s_gltf_0(1278)
#define _s_gltf_target _s_gltf_0(1287)
#define _s_gltf_targets _s_gltf_0(1294)
#define _s_gltf_targetNames _s_gltf_0(1302)
#define _s_gltf_morphPresets _s_gltf_0(1314)
#define _s_gltf_path _s_gltf_0(1327)
#define _s_gltf_pointer _s_gltf_0(1332)
#define _s_gltf_interpolation _s_gltf_0(1340)
#define _s_gltf_input _s_gltf_0(1354)
#define _s_gltf_output _s_gltf_0(1360)
#define _s_gltf_anim _s_gltf_0(1367)
#define _s_gltf_LINEAR _s_gltf_0(1372)
#define _s_gltf_STEP _s_gltf_0(1379)
#define _s_gltf_CUBICSPLINE _s_gltf_0(1384)
#define _s_gltf_inverseBindMatrices _s_gltf_0(1396)
#define _s_gltf_joints _s_gltf_0(1416)
#define _s_gltf_skeleton _s_gltf_0(1423)
#define _s_gltf_sparse _s_gltf_0(1432)
#define _s_gltf_b64d _s_gltf_0(1439)
#define _s_gltf_offset _s_gltf_0(1445)
#define _s_gltf_fallback _s_gltf_0(1452)
#define _s_gltf_filter _s_gltf_0(1461)
#define _s_gltf_ATTRIBUTES _s_gltf_0(1468)
#define _s_gltf_TRIANGLES _s_gltf_0(1479)
#define _s_gltf_INDICES _s_gltf_0(1489)
#define _s_gltf_NONE _s_gltf_0(1497)
#define _s_gltf_OCTAHEDRAL _s_gltf_0(1502)
#define _s_gltf_QUATERNION _s_gltf_0(1513)
#define _s_gltf_EXPONENTIAL _s_gltf_0(1524)
#define _s_gltf_KHR_texture_transform _s_gltf_0(1536)
#define _s_gltf_KHR_animation_pointer _s_gltf_0(1558)
#define _s_gltf_KHR_node_visibility _s_gltf_0(1580)
#define _s_gltf_KHR_draco_mesh_compression _s_gltf_0(1600)
#define _s_gltf_KHR_mesh_quantization _s_gltf_0(1627)
#define _s_gltf_KHR_meshopt_compression _s_gltf_0(1649)
#define _s_gltf_EXT_meshopt_compression _s_gltf_0(1673)
#define _s_gltf_EXT_mesh_gpu_instancing _s_gltf_0(1697)
#define _s_gltf_EXT_texture_webp _s_gltf_0(1721)
#define _s_gltf_EXT_lights_image_based _s_gltf_0(1738)
#define _s_gltf_EXT_lights_ies _s_gltf_0(1761)
#define _s_gltf_EXT_mesh_manifold _s_gltf_0(1776)
#define _s_gltf_EXT_mesh_primitive_restart _s_gltf_0(1794)
#define _s_gltf_EXT_texture_astc _s_gltf_0(1821)
#define _s_gltf_EXT_gsplat_compression_spz _s_gltf_0(1838)
#define _s_gltf_ADOBE_materials_clearcoat_specular _s_gltf_0(1865)
#define _s_gltf_ADOBE_materials_clearcoat_tint _s_gltf_0(1900)
#define _s_gltf_ADOBE_materials_thin_transparency _s_gltf_0(1931)
#define _s_gltf_AGI_articulations _s_gltf_0(1965)
#define _s_gltf_AGI_stk_metadata _s_gltf_0(1983)
#define _s_gltf_CESIUM_primitive_outline _s_gltf_0(2000)
#define _s_gltf_FB_geometry_metadata _s_gltf_0(2025)

/* _s_gltf_pool_1 */
#define _s_gltf_GODOT_single_root _s_gltf_1(0)
#define _s_gltf_GRIFFEL_bim_data _s_gltf_1(18)
#define _s_gltf_MPEG_accessor_timed _s_gltf_1(35)
#define _s_gltf_MPEG_animation_timing _s_gltf_1(55)
#define _s_gltf_MPEG_audio_spatial _s_gltf_1(77)
#define _s_gltf_MPEG_buffer_circular _s_gltf_1(96)
#define _s_gltf_MPEG_media _s_gltf_1(117)
#define _s_gltf_MPEG_mesh_linking _s_gltf_1(128)
#define _s_gltf_MPEG_scene_dynamic _s_gltf_1(146)
#define _s_gltf_MPEG_texture_video _s_gltf_1(165)
#define _s_gltf_MPEG_viewport_recommended _s_gltf_1(184)
#define _s_gltf_MSFT_lod _s_gltf_1(210)
#define _s_gltf_MSFT_packing_normalRoughnessMetallic _s_gltf_1(219)
#define _s_gltf_MSFT_packing_occlusionRoughnessMetallic _s_gltf_1(256)
#define _s_gltf_MSFT_texture_dds _s_gltf_1(296)
#define _s_gltf_NV_materials_mdl _s_gltf_1(313)
#define _s_gltf_KHR_lights_punctual _s_gltf_1(330)
#define _s_gltf_KHR_materials_variants _s_gltf_1(350)
#define _s_gltf_KHR_texture_basisu _s_gltf_1(373)
#define _s_gltf_KHR_techniques_webgl _s_gltf_1(392)
#define _s_gltf_KHR_xmp _s_gltf_1(413)
#define _s_gltf_KHR_xmp_json_ld _s_gltf_1(421)
#define _s_gltf_KHR_gaussian_splatting _s_gltf_1(437)
#define _s_gltf_packet _s_gltf_1(460)
#define _s_gltf_packets _s_gltf_1(467)
#define _s_gltf_kernel _s_gltf_1(475)
#define _s_gltf_colorSpace _s_gltf_1(482)
#define _s_gltf_projection _s_gltf_1(493)
#define _s_gltf_sortingMethod _s_gltf_1(504)
#define _s_gltf_compression _s_gltf_1(518)
#define _s_gltf_format _s_gltf_1(530)
#define _s_gltf_spz _s_gltf_1(537)
#define _s_gltf_variants _s_gltf_1(541)
#define _s_gltf_mappings _s_gltf_1(550)
#define _s_gltf_variant _s_gltf_1(559)
#define _s_gltf_KHR_materials_clearcoat _s_gltf_1(567)
#define _s_gltf_clearcoatFactor _s_gltf_1(591)
#define _s_gltf_clearcoatTexture _s_gltf_1(607)
#define _s_gltf_clearcoatRoughnessFactor _s_gltf_1(624)
#define _s_gltf_clearcoatRoughnessTexture _s_gltf_1(649)
#define _s_gltf_clearcoatNormalTexture _s_gltf_1(675)
#define _s_gltf_KHR_materials_ior _s_gltf_1(698)
#define _s_gltf_ior _s_gltf_1(716)
#define _s_gltf_KHR_materials_unlit _s_gltf_1(720)
#define _s_gltf_KHR_materials_emissive_strength _s_gltf_1(740)
#define _s_gltf_emissiveStrength _s_gltf_1(772)
#define _s_gltf_KHR_materials_transmission _s_gltf_1(789)
#define _s_gltf_transmissionFactor _s_gltf_1(816)
#define _s_gltf_transmissionTexture _s_gltf_1(835)
#define _s_gltf_KHR_materials_sheen _s_gltf_1(855)
#define _s_gltf_sheenColorFactor _s_gltf_1(875)
#define _s_gltf_sheenColorTexture _s_gltf_1(892)
#define _s_gltf_sheenRoughnessFactor _s_gltf_1(910)
#define _s_gltf_sheenRoughnessTexture _s_gltf_1(931)
#define _s_gltf_KHR_materials_iridescence _s_gltf_1(953)
#define _s_gltf_iridescenceFactor _s_gltf_1(979)
#define _s_gltf_iridescenceTexture _s_gltf_1(997)
#define _s_gltf_iridescenceIor _s_gltf_1(1016)
#define _s_gltf_iridescenceThicknessMinimum _s_gltf_1(1031)
#define _s_gltf_iridescenceThicknessMaximum _s_gltf_1(1059)
#define _s_gltf_iridescenceThicknessTexture _s_gltf_1(1087)
#define _s_gltf_KHR_materials_volume _s_gltf_1(1115)
#define _s_gltf_thicknessFactor _s_gltf_1(1136)
#define _s_gltf_thicknessTexture _s_gltf_1(1152)
#define _s_gltf_attenuationDistance _s_gltf_1(1169)
#define _s_gltf_attenuationColor _s_gltf_1(1189)
#define _s_gltf_KHR_materials_anisotropy _s_gltf_1(1206)
#define _s_gltf_anisotropyStrength _s_gltf_1(1231)
#define _s_gltf_anisotropyRotation _s_gltf_1(1250)
#define _s_gltf_anisotropyTexture _s_gltf_1(1269)
#define _s_gltf_KHR_materials_dispersion _s_gltf_1(1287)
#define _s_gltf_dispersion _s_gltf_1(1312)
#define _s_gltf_KHR_materials_diffuse_transmission _s_gltf_1(1323)
#define _s_gltf_diffuseTransmissionFactor _s_gltf_1(1358)
#define _s_gltf_diffuseTransmissionTexture _s_gltf_1(1384)
#define _s_gltf_diffuseTransmissionColorFactor _s_gltf_1(1411)
#define _s_gltf_diffuseTransmissionColorTexture _s_gltf_1(1442)

#endif /* gltf_strpool_h */
