/*
 * Copyright (C) 2020 Recep Aslantas
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef gltf_strpool_h
#  define gltf_strpool_h

#ifndef _GLTF_STRPOOL_
#  define _AK_EXTERN extern
#else
#  define _AK_EXTERN
#endif

_AK_EXTERN const char _s_gltf_pool_0[];
_AK_EXTERN const char _s_gltf_pool_1[];

#define _s_gltf_0(x) (_s_gltf_pool_0 + x)
#define _s_gltf_1(x) (_s_gltf_pool_1 + x)

/* _s_gltf_pool_0 */
#define _s_gltf_space _s_gltf_0(0)
#define _s_gltf_gltf _s_gltf_0(2)
#define _s_gltf_asset _s_gltf_0(7)
#define _s_gltf_version _s_gltf_0(13)
#define _s_gltf_generator _s_gltf_0(21)
#define _s_gltf_copyright _s_gltf_0(31)
#define _s_gltf_meter _s_gltf_0(41)
#define _s_gltf_buffers _s_gltf_0(47)
#define _s_gltf_uri _s_gltf_0(55)
#define _s_gltf_byteLength _s_gltf_0(59)
#define _s_gltf_bufferViews _s_gltf_0(70)
#define _s_gltf_buffer _s_gltf_0(82)
#define _s_gltf_byteOffset _s_gltf_0(89)
#define _s_gltf_byteStride _s_gltf_0(100)
#define _s_gltf_bufferView _s_gltf_0(111)
#define _s_gltf_componentType _s_gltf_0(122)
#define _s_gltf_normalized _s_gltf_0(136)
#define _s_gltf_count _s_gltf_0(147)
#define _s_gltf_type _s_gltf_0(153)
#define _s_gltf_max _s_gltf_0(158)
#define _s_gltf_min _s_gltf_0(162)
#define _s_gltf_values _s_gltf_0(166)
#define _s_gltf_meshes _s_gltf_0(173)
#define _s_gltf_primitives _s_gltf_0(180)
#define _s_gltf_attributes _s_gltf_0(191)
#define _s_gltf_indices _s_gltf_0(202)
#define _s_gltf_mode _s_gltf_0(210)
#define _s_gltf_nodes _s_gltf_0(215)
#define _s_gltf_node _s_gltf_0(221)
#define _s_gltf_mesh _s_gltf_0(226)
#define _s_gltf_scene _s_gltf_0(231)
#define _s_gltf_scenes _s_gltf_0(237)
#define _s_gltf_name _s_gltf_0(244)
#define _s_gltf_accessors _s_gltf_0(249)
#define _s_gltf_POSITION _s_gltf_0(259)
#define _s_gltf_NORMAL _s_gltf_0(268)
#define _s_gltf_TANGENT _s_gltf_0(275)
#define _s_gltf_TEXCOORD _s_gltf_0(283)
#define _s_gltf_COLOR _s_gltf_0(292)
#define _s_gltf_JOINTS _s_gltf_0(298)
#define _s_gltf_WEIGHTS _s_gltf_0(305)
#define _s_gltf_SCALAR _s_gltf_0(313)
#define _s_gltf_VEC2 _s_gltf_0(320)
#define _s_gltf_VEC3 _s_gltf_0(325)
#define _s_gltf_VEC4 _s_gltf_0(330)
#define _s_gltf_MAT2 _s_gltf_0(335)
#define _s_gltf_MAT3 _s_gltf_0(340)
#define _s_gltf_MAT4 _s_gltf_0(345)
#define _s_gltf_children _s_gltf_0(350)
#define _s_gltf_matrix _s_gltf_0(359)
#define _s_gltf_rotation _s_gltf_0(366)
#define _s_gltf_scale _s_gltf_0(375)
#define _s_gltf_translation _s_gltf_0(381)
#define _s_gltf_weights _s_gltf_0(393)
#define _s_gltf_extensions _s_gltf_0(401)
#define _s_gltf_extensionsRequired _s_gltf_0(412)
#define _s_gltf_extras _s_gltf_0(431)
#define _s_gltf_skin _s_gltf_0(438)
#define _s_gltf_morph _s_gltf_0(443)
#define _s_gltf_skins _s_gltf_0(449)
#define _s_gltf_camera _s_gltf_0(455)
#define _s_gltf_cameras _s_gltf_0(462)
#define _s_gltf_light _s_gltf_0(470)
#define _s_gltf_lights _s_gltf_0(476)
#define _s_gltf_visible _s_gltf_0(483)
#define _s_gltf_color _s_gltf_0(491)
#define _s_gltf_intensity _s_gltf_0(497)
#define _s_gltf_range _s_gltf_0(507)
#define _s_gltf_spot _s_gltf_0(513)
#define _s_gltf_innerConeAngle _s_gltf_0(518)
#define _s_gltf_outerConeAngle _s_gltf_0(533)
#define _s_gltf_directional _s_gltf_0(548)
#define _s_gltf_point _s_gltf_0(560)
#define _s_gltf_perspective _s_gltf_0(566)
#define _s_gltf_orthographic _s_gltf_0(578)
#define _s_gltf_aspectRatio _s_gltf_0(591)
#define _s_gltf_xfov _s_gltf_0(603)
#define _s_gltf_yfov _s_gltf_0(608)
#define _s_gltf_zfar _s_gltf_0(613)
#define _s_gltf_znear _s_gltf_0(618)
#define _s_gltf_xmag _s_gltf_0(624)
#define _s_gltf_ymag _s_gltf_0(629)
#define _s_gltf_ak_flg _s_gltf_0(634)
#define _s_gltf_VERTEX _s_gltf_0(641)
#define _s_gltf_images _s_gltf_0(648)
#define _s_gltf_image _s_gltf_0(655)
#define _s_gltf_sampler _s_gltf_0(661)
#define _s_gltf_samplers _s_gltf_0(669)
#define _s_gltf_wrapS _s_gltf_0(678)
#define _s_gltf_wrapT _s_gltf_0(684)
#define _s_gltf_magFilter _s_gltf_0(690)
#define _s_gltf_minFilter _s_gltf_0(700)
#define _s_gltf_textures _s_gltf_0(710)
#define _s_gltf_source _s_gltf_0(719)
#define _s_gltf_material _s_gltf_0(726)
#define _s_gltf_materials _s_gltf_0(735)
#define _s_gltf_pbrMetalRough _s_gltf_0(745)
#define _s_gltf_normalTex _s_gltf_0(766)
#define _s_gltf_occlusionTex _s_gltf_0(780)
#define _s_gltf_strength _s_gltf_0(797)
#define _s_gltf_emissiveTex _s_gltf_0(806)
#define _s_gltf_emissiveFac _s_gltf_0(822)
#define _s_gltf_alphaMode _s_gltf_0(837)
#define _s_gltf_alphaCutoff _s_gltf_0(847)
#define _s_gltf_doubleSided _s_gltf_0(859)
#define _s_gltf_baseColor _s_gltf_0(871)
#define _s_gltf_baseColorTex _s_gltf_0(887)
#define _s_gltf_metalFac _s_gltf_0(904)
#define _s_gltf_roughFac _s_gltf_0(919)
#define _s_gltf_metalRoughTex _s_gltf_0(935)
#define _s_gltf_index _s_gltf_0(960)
#define _s_gltf_texCoord _s_gltf_0(966)
#define _s_gltf_texcoordPrefix _s_gltf_0(975)
#define _s_gltf_sid_sampler _s_gltf_0(984)
#define _s_gltf_id_specgloss _s_gltf_0(988)
#define _s_gltf_ext_pbrSpecGloss _s_gltf_0(998)
#define _s_gltf_ext_KHR_materials_specular _s_gltf_0(1034)
#define _s_gltf_ext_KHR_materials_ior _s_gltf_0(1057)
#define _s_gltf_specularFactor _s_gltf_0(1075)
#define _s_gltf_specularTexture _s_gltf_0(1090)
#define _s_gltf_specularColorFactor _s_gltf_0(1106)
#define _s_gltf_specularColorTexture _s_gltf_0(1126)
#define _s_gltf_diffuseFactor _s_gltf_0(1147)
#define _s_gltf_specFactor _s_gltf_0(1161)
#define _s_gltf_diffuseTexture _s_gltf_0(1176)
#define _s_gltf_glossFactor _s_gltf_0(1191)
#define _s_gltf_specGlossTex _s_gltf_0(1208)
#define _s_gltf_BLEND _s_gltf_0(1234)
#define _s_gltf_MASK _s_gltf_0(1240)
#define _s_gltf_OPAQUE _s_gltf_0(1245)
#define _s_gltf_animations _s_gltf_0(1252)
#define _s_gltf_channels _s_gltf_0(1263)
#define _s_gltf_target _s_gltf_0(1272)
#define _s_gltf_targets _s_gltf_0(1279)
#define _s_gltf_targetNames _s_gltf_0(1287)
#define _s_gltf_morphPresets _s_gltf_0(1299)
#define _s_gltf_path _s_gltf_0(1312)
#define _s_gltf_pointer _s_gltf_0(1317)
#define _s_gltf_interpolation _s_gltf_0(1325)
#define _s_gltf_input _s_gltf_0(1339)
#define _s_gltf_output _s_gltf_0(1345)
#define _s_gltf_anim _s_gltf_0(1352)
#define _s_gltf_LINEAR _s_gltf_0(1357)
#define _s_gltf_STEP _s_gltf_0(1364)
#define _s_gltf_CUBICSPLINE _s_gltf_0(1369)
#define _s_gltf_inverseBindMatrices _s_gltf_0(1381)
#define _s_gltf_joints _s_gltf_0(1401)
#define _s_gltf_skeleton _s_gltf_0(1408)
#define _s_gltf_sparse _s_gltf_0(1417)
#define _s_gltf_b64d _s_gltf_0(1424)
#define _s_gltf_offset _s_gltf_0(1430)
#define _s_gltf_fallback _s_gltf_0(1437)
#define _s_gltf_filter _s_gltf_0(1446)
#define _s_gltf_ATTRIBUTES _s_gltf_0(1453)
#define _s_gltf_TRIANGLES _s_gltf_0(1464)
#define _s_gltf_INDICES _s_gltf_0(1474)
#define _s_gltf_NONE _s_gltf_0(1482)
#define _s_gltf_OCTAHEDRAL _s_gltf_0(1487)
#define _s_gltf_QUATERNION _s_gltf_0(1498)
#define _s_gltf_EXPONENTIAL _s_gltf_0(1509)
#define _s_gltf_KHR_texture_transform _s_gltf_0(1521)
#define _s_gltf_KHR_animation_pointer _s_gltf_0(1543)
#define _s_gltf_KHR_node_visibility _s_gltf_0(1565)
#define _s_gltf_KHR_draco_mesh_compression _s_gltf_0(1585)
#define _s_gltf_KHR_mesh_quantization _s_gltf_0(1612)
#define _s_gltf_KHR_meshopt_compression _s_gltf_0(1634)
#define _s_gltf_EXT_meshopt_compression _s_gltf_0(1658)
#define _s_gltf_EXT_mesh_gpu_instancing _s_gltf_0(1682)
#define _s_gltf_EXT_texture_webp _s_gltf_0(1706)
#define _s_gltf_EXT_lights_image_based _s_gltf_0(1723)
#define _s_gltf_EXT_lights_ies _s_gltf_0(1746)
#define _s_gltf_EXT_mesh_manifold _s_gltf_0(1761)
#define _s_gltf_EXT_mesh_primitive_restart _s_gltf_0(1779)
#define _s_gltf_EXT_texture_astc _s_gltf_0(1806)
#define _s_gltf_ADOBE_materials_clearcoat_specular _s_gltf_0(1823)
#define _s_gltf_ADOBE_materials_clearcoat_tint _s_gltf_0(1858)
#define _s_gltf_ADOBE_materials_thin_transparency _s_gltf_0(1889)
#define _s_gltf_AGI_articulations _s_gltf_0(1923)
#define _s_gltf_AGI_stk_metadata _s_gltf_0(1941)
#define _s_gltf_CESIUM_primitive_outline _s_gltf_0(1958)
#define _s_gltf_FB_geometry_metadata _s_gltf_0(1983)
#define _s_gltf_GODOT_single_root _s_gltf_0(2004)
#define _s_gltf_GRIFFEL_bim_data _s_gltf_0(2022)

/* _s_gltf_pool_1 */
#define _s_gltf_MPEG_accessor_timed _s_gltf_1(0)
#define _s_gltf_MPEG_animation_timing _s_gltf_1(20)
#define _s_gltf_MPEG_audio_spatial _s_gltf_1(42)
#define _s_gltf_MPEG_buffer_circular _s_gltf_1(61)
#define _s_gltf_MPEG_media _s_gltf_1(82)
#define _s_gltf_MPEG_mesh_linking _s_gltf_1(93)
#define _s_gltf_MPEG_scene_dynamic _s_gltf_1(111)
#define _s_gltf_MPEG_texture_video _s_gltf_1(130)
#define _s_gltf_MPEG_viewport_recommended _s_gltf_1(149)
#define _s_gltf_MSFT_lod _s_gltf_1(175)
#define _s_gltf_MSFT_packing_normalRoughnessMetallic _s_gltf_1(184)
#define _s_gltf_MSFT_packing_occlusionRoughnessMetallic _s_gltf_1(221)
#define _s_gltf_MSFT_texture_dds _s_gltf_1(261)
#define _s_gltf_NV_materials_mdl _s_gltf_1(278)
#define _s_gltf_KHR_lights_punctual _s_gltf_1(295)
#define _s_gltf_KHR_materials_variants _s_gltf_1(315)
#define _s_gltf_KHR_texture_basisu _s_gltf_1(338)
#define _s_gltf_KHR_xmp_json_ld _s_gltf_1(357)
#define _s_gltf_KHR_gaussian_splatting _s_gltf_1(373)
#define _s_gltf_packet _s_gltf_1(396)
#define _s_gltf_packets _s_gltf_1(403)
#define _s_gltf_kernel _s_gltf_1(411)
#define _s_gltf_colorSpace _s_gltf_1(418)
#define _s_gltf_projection _s_gltf_1(429)
#define _s_gltf_sortingMethod _s_gltf_1(440)
#define _s_gltf_compression _s_gltf_1(454)
#define _s_gltf_format _s_gltf_1(466)
#define _s_gltf_spz _s_gltf_1(473)
#define _s_gltf_variants _s_gltf_1(477)
#define _s_gltf_mappings _s_gltf_1(486)
#define _s_gltf_variant _s_gltf_1(495)
#define _s_gltf_KHR_materials_clearcoat _s_gltf_1(503)
#define _s_gltf_clearcoatFactor _s_gltf_1(527)
#define _s_gltf_clearcoatTexture _s_gltf_1(543)
#define _s_gltf_clearcoatRoughnessFactor _s_gltf_1(560)
#define _s_gltf_clearcoatRoughnessTexture _s_gltf_1(585)
#define _s_gltf_clearcoatNormalTexture _s_gltf_1(611)
#define _s_gltf_KHR_materials_ior _s_gltf_1(634)
#define _s_gltf_ior _s_gltf_1(652)
#define _s_gltf_KHR_materials_unlit _s_gltf_1(656)
#define _s_gltf_KHR_materials_emissive_strength _s_gltf_1(676)
#define _s_gltf_emissiveStrength _s_gltf_1(708)
#define _s_gltf_KHR_materials_transmission _s_gltf_1(725)
#define _s_gltf_transmissionFactor _s_gltf_1(752)
#define _s_gltf_transmissionTexture _s_gltf_1(771)
#define _s_gltf_KHR_materials_sheen _s_gltf_1(791)
#define _s_gltf_sheenColorFactor _s_gltf_1(811)
#define _s_gltf_sheenColorTexture _s_gltf_1(828)
#define _s_gltf_sheenRoughnessFactor _s_gltf_1(846)
#define _s_gltf_sheenRoughnessTexture _s_gltf_1(867)
#define _s_gltf_KHR_materials_iridescence _s_gltf_1(889)
#define _s_gltf_iridescenceFactor _s_gltf_1(915)
#define _s_gltf_iridescenceTexture _s_gltf_1(933)
#define _s_gltf_iridescenceIor _s_gltf_1(952)
#define _s_gltf_iridescenceThicknessMinimum _s_gltf_1(967)
#define _s_gltf_iridescenceThicknessMaximum _s_gltf_1(995)
#define _s_gltf_iridescenceThicknessTexture _s_gltf_1(1023)
#define _s_gltf_KHR_materials_volume _s_gltf_1(1051)
#define _s_gltf_thicknessFactor _s_gltf_1(1072)
#define _s_gltf_thicknessTexture _s_gltf_1(1088)
#define _s_gltf_attenuationDistance _s_gltf_1(1105)
#define _s_gltf_attenuationColor _s_gltf_1(1125)
#define _s_gltf_KHR_materials_anisotropy _s_gltf_1(1142)
#define _s_gltf_anisotropyStrength _s_gltf_1(1167)
#define _s_gltf_anisotropyRotation _s_gltf_1(1186)
#define _s_gltf_anisotropyTexture _s_gltf_1(1205)
#define _s_gltf_KHR_materials_dispersion _s_gltf_1(1223)
#define _s_gltf_dispersion _s_gltf_1(1248)
#define _s_gltf_KHR_materials_diffuse_transmission _s_gltf_1(1259)
#define _s_gltf_diffuseTransmissionFactor _s_gltf_1(1294)
#define _s_gltf_diffuseTransmissionTexture _s_gltf_1(1320)
#define _s_gltf_diffuseTransmissionColorFactor _s_gltf_1(1347)
#define _s_gltf_diffuseTransmissionColorTexture _s_gltf_1(1378)

#endif /* gltf_strpool_h */
